doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}

    default_database: mongoLL

    document_managers:
        default:
            auto_mapping: false  
            mappings:
                App:
                    is_bundle: false
                    type: attribute   
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
