

services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
      - mongo

  nginx:
    image: nginx:alpine
    container_name: lovelire_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:16
    container_name: lovelire_postgres
    environment:
      POSTGRES_DB: lovelire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: lovelire_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
