version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lovelire_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: prod
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URL: ${MONGODB_URL}
      JWT_PASSPHRASE: lovelire
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:16
    container_name: lovelire_postgres
    environment:
      POSTGRES_DB: lovelire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: lovelire_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
