services:
  - type: web
    name: symfony-app
    env: docker
    dockerfilePath: ./php/Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
    plan: free
    region: frankfurt
    branch: main