services:
  - type: web
    name: lovelire-app
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    branch: main
    envVars:
      - key: APP_ENV
        value: prod
      - key: JWT_PRIVATE_KEY
        fromSecret: jwt-private-key
      - key: JWT_PUBLIC_KEY
        fromSecret: jwt-public-key
      - key: DATABASE_URL
        fromSecret: db-url
      - key: MONGODB_URL
        fromSecret: mongo-url
      - key: JWT_PASSPHRASE
        value: lovelire
