parameters:
    covers_directory: '%kernel.project_dir%/public/uploads/covers'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\JWTLoginSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\Security\CookieTokenExtractor:
        arguments:
            $cookieName: 'BEARER'
        tags:
            - { name: 'lexik_jwt_authentication.token_extractor', priority: 100 }

    App\Service\MongoDBService:
        arguments:
            $mongoManager: '@doctrine_mongodb.odm.document_manager'
